elixir-circuits/circuits_gpio

README.md, lib/elixir_ale.ex, lib/gpio.ex, lib/gpio/nif.ex, mix.exs, src/gpio_nif.c
There are few questions I have, but I think we adjust over time. I was just trying to remove the reference to ElixirALE while keeping sensible documentation.
I tested using your GPIO-NOTES.md and all code seems to be still working in accordance with that.
=> Remove elixir_ale from source

README.md, lib/gpio.ex, lib/gpio/gpio_nif.ex, src/gpio_nif.c
Add pin/1 function to retrieve GPIO pin number for a reference.
Update README to document pin and set_pull_mode functions
=> Add pin 1 function

.gitignore, README.md, lib/gpio.ex, lib/gpio/gpio_nif.ex, mix.exs, src/gpio_nif.c, src/gpio_nif.h
This seems to be the best option for easy to type and not too generic.
I also added back the NIF checking code so that it's possible to build docs on OSX.
=> Rename package to circuits_gpio/Circuits.GPIO

lib/gpio.ex, src/gpio_nif.c
The intention here is to simplify the API by removing the need for users to check for `{:error, reason}`. I can't think of any way that an error could occur that isn't a programming mistake (writing to an input) or something truly exceptional (someone unmounts the sysfs partition or loads a device tree overlay that changes the gpio).
Fixes #14.
=> Raise exceptions on read and write instead of returning error tuples

PORTING.md, README.md, lib/gpio.ex, lib/gpio/gpio_nif.ex, src/gpio_nif.c, src/gpio_nif.h, src/hal_stub.c, src/hal_sysfs.c, src/hal_sysfs_interrupts.c, test/circuits_gpio_test.exs
This fixes #21. The desire is to improve the name of the function to
make it more obvious what it does (i.e. configure the sending of
messages when the line changes state). See the issue for the discussion.
=> Rename set_edge_mode to set_interrupts

lib/gpio.ex, lib/gpio/gpio_nif.ex, src/gpio_nif.c, src/gpio_nif.h, src/hal_stub.c, src/hal_sysfs.c, test/circuits_gpio_test.exs
This change is also needed to open a GPIO more than once as an output.
Sysfs initializes outputs to 0 when setting the GPIO's direction. This
changes the direction logic so that it checks the direction before
setting it if the output should retain its value.
=> Support glitch-free output initialization

.circleci/config.yml, Makefile, mix.exs, mix.lock
When switching between mix targets, the C build products need to be
stored in separate build directories or the wrong ones will be used.
This passes the build directory to the Makefile in the $PREFIX
environment variable. Using $PREFIX is a C convention for specifying the
base install directory.
If this project is being included as a dependency, the top level
`mix.exs` must have `build_embedded: true`. If `build_embedded` is
`false`, then the `priv` directory will be a symlink to a common
directory and this won't work.
=> Pass build path to Makefile

README.md, lib/gpio.ex, src/hal_stub.c, src/hal_sysfs_interrupts.c, test/circuits_gpio_test.exs
Closes #31 
In the issue, you said `circuits_uart` (that is circuit with an `s`), but wanted to change `gpio` to `circuit_gpio`. I assumed that you meant to add an `s` at the end of `circuit` as the org is `Elixir Circuits` and UART is `circuits_uart`, let me know if you meant without an `s`.
Still needs to be exercised on real hardware.
=> gpio->circuits_gpio message label

Makefile, PORTING.md, mix.exs, mix.lock
`elixir_make` was just updated to include several of the variables that we manually defined. This change bumps the `elixir_make` and takes advantage of those new variables to simplify the `mix.exs`.
=> Simplifications

README.md
This just removes the existing line regarding internal pull-up/pull-down
resistors as it's no longer accurate:
> It's platform-dependent and not shown here.
It's been replaced with a link to the `Circuits.GPIO.set_pull_mode`
section.
I've been waiting for this feature, but didn't realize it was added because I stopped reading when I encountered this line. Hopefully, this clears it up for others.
Thanks for considering.
=> Update internal pull-up/pull-down wording in README

src/hal_sysfs.c
As discussed in #45, this is a race condition where it may take a few ticks for the symlink to be created. Wait up to 1 second, although on a Raspberry Pi for example it is usually created in under 20ms
=> Avoid sysfs symlink race condition

lib/gpio.ex
Tiny documentation update for timestamps. Normally one would expect an integer timestamp to be relative to the UNIX epoch, but these are nanoseconds since the host system boot (a.la `/proc/uptime`)
=> Clarify what the interrupt timestamp value is

src/detect_target.sh, src/hal_sysfs.c
The bcm_host.h detection fix makes the pullup/pulldown feature work on Raspbian without any extra flags. This also silences the prints when the GPIO files can't be opened, since the errors are expected on Raspbian and there's no need for the user to worry about them.
=> Fix bcm_host.h detection and error printout on Raspbian

.circleci/config.yml, .circleci/md-style.rb, README.md
While this isn't an issue with circuits_gpio or any of the circuits projects, Markdown issues (bad code fences so code highlighting doesn't work, duplicate headers so linking to sections breaks) happen in other projects I'm involved with and this seemed like a good place to try this out.
=> Lint markdown files on CI

README.md
#57 
This could be a good help for everyone who tries to use the stub mode in unit tests out side the Circuits.GPIO project.
=> Add note to stub in README.md

src/hal_rpi.c, test/circuits_gpio_test.exs
Tested this change on rpi4, rpi3, and rpi2. 
Pull up/down resistor switch, works for rpi4 now, and older rpi models are not affected. 
Also fixed a test that was failing the Circle CI build.
Let me know if you have any suggested changes or other tests I should perform.
=> Implement rpi4 pullmodes

src/hal_sysfs_interrupts.c
Short glitches can be reported or suppressed. Unfortunately, the
uninitialized suppress_glitches field was left uninitialized, so its
setting was random. This fixes that setting.
=> Fix glitch suppression

Makefile
Hi,
I'm doing some tests on the 'Orange Pi PC' device.
On the device my tests work, but on my 'development pc' I have some problems performing tests without GPIO support.
I'm not found any solution to compiling stub NIF for 'mix test', even setting MIX_ENV variable to 'test' during compilation is forced to 'prod' so test involving gpio fails.
My solution is to add another variable check into makefile (`CIRCUIT_MIX_ENV`) , this made compilation compatible with previous version but allows the possibility to enable the abstraction layer compilation.
I propose this patch to correct the problem.
Thanks in advance for your work
Enrico
=> Enable "stub" hardware abstraction layer compilation on platforms without GPIO support

src/hal_sysfs.c
This lets users open GPIOs that their program is using to look at their
value without affecting the interrupt status.
The previous behavior was to set the interrupt edge state and clear out
the interrupt listener if not listening. That would cause programs to
stop seeing GPIOs change when you'd look at the GPIO. Sysfs is limited
and really only supports one GPIO user at a time, but it's reasonable to
expect that you can read a GPIO without messing up your program.
This is a safe change since there are two cases:
1. The user wants to listen for interrupts. In this case, the operation
is unchanged.
2. The user doesn't want to listen for interrupts. Now the `edge` file
isn't set and the interrupt polling thread isn't configured. This is ok,
since if `edge` is set to anything besides none, no …
=> Don't clear interrupts if not listening

src/detect_target.sh
Depending on bash flavour/version, quotes are needed in the -z check.
Quotes are more widely compatible and are required for yocto builds.
=> Fixed compatibility issue in detect_target.sh

src/hal_sysfs_interrupts.c
This fixes an issue where the NIF could not be unloaded due to the
interrupt monitoring thread never stopping. This would manifest itself
in `:init.stop` taking a long time or it breaking `runtime.exs` due to a
change that requires the VM to be restarted.
Fixes #78
=> Terminate interrupt thread on NIF unload

src/hal_sysfs.c
There are pins that have "in" direction after export, but not be activated.
These pins will not become active unless they are overwritten again.
Therefore, modified it to write always.
WHY: not apply this modifying for "out"
Because overwriting "out" has a side effect of changing the GPIO value.
=> modify hal_apply_direction/1 for pins not activated "in" by simply exporting

lib/gpio.ex
A long time ago we made an Erlang wrapper so that the library was friendlier to
use from Erlang code. Based on support requests I don't think anyone uses it.
This PR removes it so that we don't have to maintain it going forward. I can't
think of any other Elixir library that maintains an Erlang wrapper and my
experience with many Erlang programmers is that they'd prefer to reimplement an
Elixir library (especially a small one like this) than pull in the Elixir
runtime.
If this PR doesn't get any push back, my plan to remove the Erlang wrappers from
the other Circuits libraries as well.
=> Remove Erlang wrapper

c_src/gpio_nif.c, c_src/gpio_nif.h, c_src/nif_utils.c
See https://erlangforums.com/t/atom-hashing-performance/2369/5.
=> Move common NIF atoms to globals per best practice

c_src/hal_stub.c, lib/gpio.ex, lib/gpio/gpio_nif.ex
This change moves the NIF load from the time at which the module is
loaded to the time when a GPIO actually needs to be used.
The primary motivation for doing this is to defer native code crashes
from happening at load time to the time of first use. Load time is
harder to debug and sometimes its not clear which NIF caused the crash.
=> Defer loading the NIF until opening a GPIO

c_src/hal_sysfs.c
As of Linux 5.15, the AM335x GPIO banks got reordered and this throws off the pin numbering. See comments for more details. The gist is that we hide it from existing programs to avoid the new mapping that's different from almost every Beaglebone doc on the web. This will make programs work with the caveat that anyone doing manual debugging of sysfs will notice it, be confused, and hopefully find this commit.
The future has been to switch to cdev, but that's not happening in the v1.x branch so this is the workaround to allow Linux 5.15 and later.
=> Add hack to handle BBB GPIO remapping

lib/gpio.ex, lib/gpio/backend.ex, lib/gpio/cdev.ex, lib/gpio/nil_backend.ex, test/circuits_gpio_test.exs
The GPIO enumeration rarely changes so this caches the results in
`:persistent_term`. To be safe, whenever a GPIO isn't found, the
enumeration is redone.
This optimises for the common cases where a set of GPIOs are opened on
boot and then only re-opened on GenServer restarts. It will also help in
the cases where the user does one-off GPIO sets or reads.
As part of this change, more tests were added to the `gpio_spec`
resolution code which fixed a few missed cases where `gpio_spec`'s that
should have resolved didn't.
=> Cache GPIO enumeration results for faster opens

README.md, c_src/gpio_nif.c, c_src/gpio_nif.h, c_src/hal_cdev_gpio.c, c_src/hal_stub.c, lib/gpio/cdev.ex, lib/gpio/line.ex, test/circuits_gpio_test.exs
The main use of gpio_spec was to describe anything that could be passed
to `open/3`. A second use was the actual controller/index tuple. Call
this second use "location" now to differentiate it.
=> Rename confusing use of gpio_spec to location

PORTING.md, c_src/gpio_nif.c, c_src/gpio_nif.h, c_src/hal_stub.c, lib/gpio.ex, lib/gpio/cdev.ex, lib/gpio/gpio_nif.ex, lib/gpio/handle.ex, test/circuits_gpio_test.exs
It wasn't implemented for the cdev backend, and I really don't think it
was that useful anyway.
=> Remove GPIO.pin/1 and associated code

c_src/gpio_nif.c, c_src/gpio_nif.h, c_src/hal_cdev_gpio.c, c_src/hal_stub.c, lib/gpio.ex, lib/gpio/backend.ex, lib/gpio/cdev.ex, lib/gpio/gpio_nif.ex, lib/gpio/handle.ex, lib/gpio/nil_backend.ex, test/circuits_gpio_test.exs
Once `gpio_info/1` got limited to static information, there wasn't a way
to get runtime configuration and other info. This lets you do that now
and populates the information with consumer, direction and pull mode. It
could be expanded in the future.
This also fixes an issue were `open/3` didn't handle controller labels
with integer offsets.
=> Add gpio_status/1 function to get runtime info

c_src/gpio_nif.c, c_src/gpio_nif.h, c_src/hal_stub.c, lib/gpio/gpio_nif.ex, test/circuits_gpio_test.exs
This happens when multiple processes call GPIO.open at the same time.
NIFs can only be loaded once only one process gets an `:ok` return. The
others get an error telling them not to do that. That's harmless so just
try calling the function again.
The included unit test starts 32 processes in a race to open the GPIO.
On my MBP, a whole bunch of the processes would get the reload error
before the fix.
Fixes #178
=> Fix race to load NIF

README.md, notebooks/basics.livemd
This is a proposal for adding Livebook notebooks to the project repository. In other words, it is about making some of our documentation compatible with Livebook, particularly explanations with code examples. 
Livebook notebooks are markdown files so they work as regular documents as well.
https://github.com/mnishiguchi/circuits_gpio/blob/923db35bf2618df69b72d0ef4512c930adebf3de/notebooks/basics.livemd
Some projects out there including [elixir-nx/axon](https://github.com/elixir-nx/axon) have a directory named `notebooks` for Livebook notebooks. We could adopt that pattern.
If we only have one notebook, we could place it at the top level.
Optionally, we could put a "Run in Livebook" button in README with a brief introduction to Nerves Livebook.
- The contents of this Livebook notebook are …
=> add Livebook notebook

lib/gpio/gpio_nif.ex, test/circuits_gpio_test.exs
It was possible to crash the BEAM by loading a completely trimmed down
shared library with multiple processes. This converts the NIF loader
back to the traditional `@on_load` way that's serialized by the code
loader. The benefits of delaying the load time are less now that the
shared library has been tested quite a bit.
=> Remove deferred loading of NIF

mix.exs
It turns out that people sometimes have MIX_TARGET set when they're not
compiling for Nerves. On MacOS which doesn't support cdev, this causes
the following error:
```
==> circuits_gpio
"**** CIRCUITS_GPIO_BACKEND set to [cdev] ****"
Makefile:44: *** Circuits.GPIO Linux cdev backend is not supported on non-Linux platforms. Review circuits_gpio backend configuration or report an issue if improperly detected..  Stop.
could not compile dependency :circuits_gpio, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile circuits_gpio --force", update it with "mix deps.update circuits_gpio" or clean it with "mix deps.clean circuits_gpio"
```
This is pretty confusing. This change makes the Nerves detection smarter
by first checking the …
=> Improve target detection for building cdev

README.md
This is a proposal for organizing migration guides. It mainly addresses two things.
1. Outdated contents in README.md
2. Introducing a new directory that holds our guides including migration instructions
- README.md still talks as if v2 had not been released yet. So it needs updating.
- Currently our upgrade guides are located in two files:
1. README.md
3. PORTING.md
- Some projects out there seem to have a dedicated directory for "guides",
which we could try now that we have more than one migration concerns
- The contents are mostly unchanged; basically they are just moved around
- Once we decide to go ahead, we will have to check the hyperlinks to `PORTING.md` since it is referenced in a few places; also included files in the package might need adjustment
=> update documentation for v2

lib/gpio.ex, test/circuits_gpio_test.exs
This addresses some confusion when `:write` was passed rather than
`:output` for the second parameter. Raising ArgumentError with the
allowed values saves a look at the docs.
This also does something similar with the gpio spec.
=> Raise ArgumentErrors with help on incorrect GPIO.open call
